### PR TITLE
added contributor section to README.md

### PR DESCRIPTION
**Pull request by jhonsnow456**
create PR for dev branch
https://github.com/Megabyte-143/certified_cliche/issues/38#issue-1156807059

### CODE REVIEW

**Comment by Megabyte-143** [comment]
It would be great if you put the images and description over here also. 
Thank You for contributing. 
Your PR will be reviewed and merge soon.

**Comment by Megabyte-143** [comment]
@jhonsnow456 You haven't made all the changes you mentioned [here](https://github.com/Megabyte-143/certified_cliche/issues/38#issuecomment-1056637220).
Please do all the changes first, then we will merge the PR.

Thank You for contributing.
_Megabyte_

**Review by raysummee — APPROVED** [review]

**Comment by raysummee** [comment]
> @jhonsnow456 You haven't made all the changes you mentioned [here](https://github.com/Megabyte-143/certified_cliche/issues/38#issuecomment-1056637220). Please do all the changes first, then we will merge the PR.
> 
> Thank You for contributing. _Megabyte_

@jhonsnow456 Please refer to this comment. I guess some changes are asked. I'll merge it after the changes are done.

**Comment by jhonsnow456** [comment]
image

**Comment by jhonsnow456** [comment]
If you could allow me I will change the entire document accordingly

**Review by raysummee — APPROVED** [review]

**Comment by Megabyte-143** [comment]
> If you could allow me I will change the entire document accordingly

Currently you have made changes by just removing the borders and changing the tags.
It might be due to restrictions,  so for that we allow you to change the format of whole Documentation in your manner. And if we find it useful and attention grabbing we will surely merge the PR. 
Other than that you may add images and other stuff, and if anything require do ket us know.

Thanks for contributing. 
_Megabyte_

**Comment by jhonsnow456** [comment]
The entire document is updated successfully.

**Comment by Megabyte-143** [comment]
Nice improvements.

**Just need a quick edit** =>
Redirect to the GitHub Profile of the Contributors after clicking on them instead of contributors page of the repo.

Thanks for contributing
_Megabyte_

**Review by raysummee — APPROVED** [review]

**Review by Megabyte-143 — APPROVED** [review]

**Pull request merged**
