### PR TITLE
PR for tabs+navbar

### PR DESCRIPTION
**Pull request by utkarshnashine**
@raysummee please check it

### CODE REVIEW

**Comment by codewhen** [comment]
@utkarshnashine Please resolve the conflicts.

**Comment by utkarshnashine** [comment]
sir by resolving the conflicts should i like just text change the version which are shown conflicting?

**Comment by utkarshnashine** [comment]
@raysummee if you can specify i will be enlightened

**Comment by codewhen** [comment]
@utkarshnashine I run your code. But I didn't see the UI implementation as required. And also you have some syntax issue in your code too. in `_app.js` file.

Please add the `navbar.js` into `_app.js` as component

and also. 

* reduce the navbar height (padding 1.5rem to 1.08rem)
* the front-weight should be 500 instead of 900

**Comment by utkarshnashine** [comment]
@raysummee can i do it tommorow as tommorow i can show you my code too and errors in the terminals also

**Comment by utkarshnashine** [comment]
i have tried changing the commit but errors and errors

**Comment by codewhen** [comment]
@utkarshnashine You just need to add the ```<Navbar/>``` to `_app.js`. 

* remove the existing code 

```
<nav
..
..
</nav>
```

 * and add the ```<navbar/>```

**Comment by utkarshnashine** [comment]
Roger that sir I will make it till night

**Comment by codewhen** [comment]
@utkarshnashine can you change the padding from `1.5rem` to `1.08rem` on the navbar -> nav tag (instead of p-6 class name). And also the font-weight should be 500 instead of 900.

Other looks good to me

**Comment by utkarshnashine** [comment]
Sure sir

**Comment by codewhen** [comment]
@utkarshnashine all looks good. But one thing is not done as mentioned.

image

As you can see in the screenshot, there is a gap below the active bar. You have to remove that. You can decrease the padding in p-6

**Comment by utkarshnashine** [comment]
Ok sir

**Comment by utkarshnashine** [comment]
@raysummee sir i have made the changes can you check them

**Comment by codewhen** [comment]
@utkarshnashine The padding issue is not solved. there is still gap below the active bar. 

Your output:

image


Expected output: 

162260700-93429b58-cc7c-4a56-b0a0-94d911d8356c

**Comment by utkarshnashine** [comment]
I thought it would be resolved

**Comment by utkarshnashine** [comment]
I will try to make it till tommorow

**Review by codewhen — APPROVED** [review]

**Review by codewhen — APPROVED** [review]

**Comment by codewhen** [comment]
@utkarshnashine 
the navbar colour should be #4A3CED
and resolve the merge conflict. this PR is ready to be merged.

* accept current commit for all (existing commit/ not yours)
* Then add you component into the _app.js like before.

**Comment by codewhen** [comment]
> @utkarshnashine the navbar colour should be #4A3CED and resolve the merge conflict. this PR is ready to be merged.
> 
> * accept current commit for all (existing commit/ not yours)
> * Then add you component into the _app.js like before.


I have already asked you to accept current commit, not yours. but you have accepted your commit there.

* index.js is not acceptable in your pr,
* _app.js is not acceptable in your pr

These above files removes some lines added by existing contributor.

As you have already accepted the wrong commits when merging, it'll be hard for you to resolve it.

**What you can do next:**

* start from the scratch (clone again and start fresh), you already have the code which should be added. so copy paste those line into the fresh clone.

Sorry for the inconvenience, I was not able to solve your conflict because the dev branch is locked.

**Comment by utkarshnashine** [comment]
ok will try to do the same

**Pull request closed without merging**
