### PR TITLE
Tabs and Navbar

### PR DESCRIPTION
**Pull request by utkarshnashine**
PR for tabs + navbar

### CODE REVIEW

**Comment by raysummee** [comment]
@utkarshnashine I left some reviews, fix those. Let me know if you can access it or not. Overall looking good 👍

**Comment by megabyte0x** [comment]
@utkarshnashine Any updates on this ?

**Comment by utkarshnashine** [comment]
It is completed all files have been changed according to details,just I need one day tommorow.as ese has disrupted the schedule

**Comment by megabyte0x** [comment]
@utkarshnashine any updates?

**Comment by utkarshnashine** [comment]
Yes sir all the files have been arranged and made,just facing some issues in how to remove unneccessary commits

**Comment by utkarshnashine** [comment]
As they are causing problem with vercel should I clone it again?

**Comment by megabyte0x** [comment]
@utkarshnashine No need to clone again but there are conflicts in the code. Please resolve them asap.

**Pull request closed without merging**
