### PR TITLE
Added received-certificates page

### LINKED ISSUE #26: Page - Received Certificate
## Page - Received Certificate
tracking in #15 

### description:
This page is to show all the certificate of participates

### Figma page name:
* 9.received certificate

(both are the same page with different functionality)

### The folder should be like follows:
 js: components/components-name/components-name.js
 css: components/components-name/components-name.module.css

### PR DESCRIPTION
**Pull request by SaachiKaup**
Tracked in #15 and #26 
Received Certificates is the 9th Page in the [figma structure](https://www.figma.com/file/HjYi7KbugT0xsXoA7arIN2/Untitled?node-id=0%3A1).

Change: Added received-certificates.js page to client/pages folder. Page made according to figma design.

### CODE REVIEW

**Comment by codewhen** [comment]
@SaachiKaup You have to use NFTCard components for each card. And instead of flex, try using grid.

**Comment by codewhen** [comment]
@SaachiKaup You have to use NFTCard components for each card. And instead of flex, try using grid.

**Comment by SaachiKaup** [comment]
> @SaachiKaup You have to use NFTCard components for each card. And instead of flex, try using grid.

Will do both.

**Comment by SaachiKaup** [comment]
Please let me know if the new changes are appropriate. The page does not match the figma prototype due to spacing issues. I was not able to fix the problem. If the code is not up to the mark, please unassign me from the issue. 
Regards,
Saachi Kaup

**Review by codewhen — APPROVED** [review]

**Pull request merged**
