### PR TITLE
Created Page - Select Role #22

### PR DESCRIPTION
**Pull request by Supriya2922**
##**What changes were made ?**

1. Created a new page called home.js ( client/pages/home.js )  and copy pasted all the content that was in index.js -->home.js  
2. added  <Link href="/home">  in client/pages/_app.js
3. created the select-role page in client/pages/index.js after deleting the initial content present in index.js
4. added two images  **client/public/Individual.png**  and  **client/public/organization.png**
5. The select-role page is responsive.

##**Why these changes were made?**

1. Since select-role page needs to appear as soon as the website loads , it should be placed in index.js as router will automatically route files named 'index' to root of directory '/'
2. Since there were already few contents of in index.js, I created a new page client/pages/home.js and copy pasted its contents and changed the routing in  client/pages/_app.js --> added  <Link href="/home">
3. Reason for change No.4 was to add them in Select-role page 

##Screenshots
select-role1

select-role
  
##Enhancements to be done.
Adding few hover animations.

PS: This is my first PR .If anything is wrong do give me few suggestions :)
#GSSOC Contributor

### CODE REVIEW

**Comment by raysummee** [comment]
@Supriya2922 `home.js` and `index.js` has the same default export function **Home**.  Please change that one then I'll merge it.

**Comment by Supriya2922** [comment]
Done :)

**Comment by raysummee** [comment]
@Supriya2922 One more thing, the select role area is filling the window height (100vh). But it should be like that, the user should see navbar, the select role area and footer without scrolling.

* The navbar will be changed after the the component is done. Tracking at #16 
* You can also add the hover effect, if you want to. 

Expected Output:
image

**Comment by raysummee** [comment]
using `vh` is not appropriate here. All device has different `dpi`. So the navbar and footer can be of different `vh`. So you have to use calc (100vh - "navbar height + footer height"px)

**Comment by Supriya2922** [comment]
I converted vh to px. Please tell me if it's the wrong way of doing it.

**Comment by raysummee** [comment]
@Supriya2922 See. For example we have a display of `1080px` in height. And another display of `760px` In height. So by using the `px` you cannot make the area fill the window. And with `vh`, the navbar and footer size in not in  `vh`, it's on `px`. So It can be converted to different `vh` in different display 

So you have to use both vh and px. There is a way to do in CSS:
```CSS
height: calc( 100vh - 50px )
```

where 50px = height of navbar + height of footer

**Comment by Supriya2922** [comment]
Ohh..Now I understood!
so in this case it'll be calc(100vh-353px)
145px-height of navbar
208px-height of footer
So 145+208=353
Right?

**Review by raysummee — APPROVED** [review]

**Comment by raysummee** [comment]
@Supriya2922 I checked your codes. It's done fantastically. I'll merge it now.

Thank you for your contribution.

**Comment by Supriya2922** [comment]
No problem :)
Thank you for suggesting better ways of implementing and guiding me through it.

**Comment by raysummee** [comment]
@Supriya2922 You're welcome. Hoping to see more contribution from you. 😄

**Pull request merged**
