### PR TITLE
fixed untracked files

### PR DESCRIPTION
**Pull request by Rajdip019**
I have fixed the gitignore so that the contacts are not committed every time. And the files inside **abi** folder is deleted because as per the instructions of first setup one has to copy those file to **abi** folder from **CONTACT**

### CODE REVIEW

**Comment by Rajdip019** [comment]
Ok got it. So should I close the issue?

**Comment by raysummee** [comment]
@Rajdip019 No. Add the .git and other files. into the gitignore. That'll be enough.

**Comment by Rajdip019** [comment]
I have done the changes! @raysummee

**Comment by raysummee** [comment]
@Rajdip019 please check the review comment I made. Fix that. And then good to merge

**Comment by raysummee** [comment]
> > @Rajdip019 please check the review comment I made. Fix that. And then good to merge
> 
> I have restored the paged in **abi**

@Rajdip019 from gitignore remove the /abi.
And add next.js specific files
refer to this: [link](https://github.com/akiran/nextjs-demo/blob/master/.gitignore).
Other files are fine. Just modify the gitignore file and add as said. 

Please let me know if any doubts are there, I'll be happy to help you.

**Comment by Rajdip019** [comment]
Ok have modified the files. @raysummee

**Comment by raysummee** [comment]
@Rajdip019 your pull request contains the old files too (the #42 files). 
Make a new fresh branch and pull it from dev branch. Do the gitignore update and make a new pull request. 

Make sure each pull request only contain the files which is related to the pull request.

And about the gitignore task. I think you have some doubt. Did you go through the link I provided. Let me make it simpler for you:

in the link: you'll find a GitHub file as:

#Logs
logs
*.log
npm-debug.log*

...

Copy paste the entire file and update the gitignore file. 

the link: [click here: https://github.com/akiran/nextjs-demo/blob/master/.gitignore](https://github.com/akiran/nextjs-demo/blob/master/.gitignore)

**Comment by raysummee** [comment]
@Rajdip019 I'm closing this PR as it is a duplicate of #45

**Pull request closed without merging**
