### PR TITLE
Another PR for tabs+navbar

### PR DESCRIPTION
**Pull request by utkarshnashine**

### CODE REVIEW

**Comment by codewhen** [comment]
@utkarshnashine can you delete the redundant folders and files. 
There are two navbar folder. and two wall.png too.

**Comment by utkarshnashine** [comment]
Should I delete it in my GitHub repo

**Comment by utkarshnashine** [comment]
And then commit it.

**Comment by utkarshnashine** [comment]
@raysummee will it be ok?

**Comment by codewhen** [comment]
@utkarshnashine yes definitely. Delete it and commit again. After that let me know once.

**Comment by utkarshnashine** [comment]
@raysummee can I make it in afternoon

**Comment by codewhen** [comment]
@utkarshnashine Sure

**Pull request closed without merging**
