### PR TITLE
Adding SnackBar

### PR DESCRIPTION
**Pull request by techSun-07**
Adding Snackbar template from Figma along with js and ts file
Screenshot (45)

### CODE REVIEW

**Comment by raysummee** [comment]
@techSun-07 #59 and #58 are the same pull request/ duplicate pull request. Please close the irrelevant one.

By the way, is this tracked through an issue? If not please make an issue before working on it and submitting the PR.

**Comment by raysummee** [comment]
@techSun-07 You are directly adding files in the root folder. The file should be in `client/pages/components/`

**Comment by megabyte0x** [comment]
@techSun-07 any updates on this ?

**Comment by megabyte0x** [comment]
@techSun-07 We are closing this pull request because of no response.

**Pull request closed without merging**
