### PR TITLE
Event Card Added

### PR DESCRIPTION
**Pull request by Rajdip019**
I have added the Event Card as a Component. I guess, this component is not used in the code anywhere for now.

This is the code I used to test it.

```
import EventCard from "./components/EventCard/EventCard";
        
 <EventCard 
          eventImage="https://i.ytimg.com/vi/CcYaZybdQYc/maxresdefault.jpg"
          eventName="Google Workspace"
          eventDesciption="Google workspace is here to attend now."
 />
 ```

Here is a image.

Screenshot 2022-03-04 003337

### CODE REVIEW

**Comment by raysummee** [comment]
@Rajdip019 the card width need to match the width of window. With a 22px or 16px of margin.

`Should be like this:`

image

`Not this:`

image

**Comment by Rajdip019** [comment]
Screenshot 2022-03-04 231150

I am making this cards!

**Comment by raysummee** [comment]
@Rajdip019 got your point, but if you hard code the width, we have to make another components for the events page right? This voids the whole concept of components. Let's make the event card like that so that, it takes the width of the parent. So that we can add this to both home page and event page. I hope you could able to understand.

**Comment by Rajdip019** [comment]
> @Rajdip019 got your point, but if you hard code the width, we have to make another components for the events page right? This voids the whole concept of components. Let's make the event card like that so that, it takes the width of the parent. So that we can add this to both home page and event page. I hope you could able to understand.

Got your point, I have made the required changes. @raysummee

**Review by raysummee — APPROVED** [review]

**Comment by raysummee** [comment]
@Rajdip019 Thank you for your contribution

**Pull request merged**
