### PR TITLE
Title of the browser tab is change from localhost to Certified-Cliche…

### LINKED ISSUE #43: Header Isuue
**Describe the bug**
For now the tab in the Brower looks like this and looks bad.
**To Reproduce**

**Expected behaviour**
 It should name Certified Cliché.

**Screenshots**
Screenshot 2022-03-02 152103

**Additional context**
Can fix this using Head tag of the next.js. Can you assign me this?

### PR DESCRIPTION
**Pull request by RaviAnand111**
… fixes#43

The title is changed from localhost to Certified Cliche

### CODE REVIEW

**Review by codewhen — APPROVED** [review]

**Comment by codewhen** [comment]
@RaviAnand111  please change the base pull request branch to `dev` from `main`.

To do that. Click edit on the top, next to pull request name.

**Comment by RaviAnand111** [comment]
Hey @raysummee, just changed the base, there are some conflicts can you help me, How can I solve these conflicts ?

**Comment by codewhen** [comment]
@RaviAnand111 there is a file called `excelToJson`, which is in this PR and it is irrelevant to the issue. Please remove that file. 

As I can see, You just did 3 line changes in `_app.js`, which is the only relevant code. 

I suggest you that, pull the new code from `dev` branch and after that add the 3 lines to it.

**Comment by codewhen** [comment]
I'm closing this PR because of no responses.

**Pull request closed without merging**
